require('dotenv').config()
const mongoose = require('mongoose')
const Salon = require('../model/Salon') // adjust the path accordingly

// replace with your own connection string
const dbURI = process.env.DB_CONNECT
const seedData = [
  {
    name: 'Urban Fringe',
    description: 'A modern salon with a touch of urban flair',
    address: '428 Edge St',
    city: 'Seattle',
    state: 'WA',
    zip: '98101',
    phone: '206-111-2222',
    email: 'contact@urbanfringe.com',
    website: 'https://urbanfringe.com',
    services: ['Styling', 'Coloring', 'Extensions'],
    employees: [],
    ratings: [],
    covidSafety: 4,
    user: '6462e5a7e0a71fef963dc856',
  },
  {
    name: 'Urban Oasis Salon',
    description: 'Relaxing urban retreat for modern beauty',
    address: '10 City Plaza',
    city: 'Chicago',
    state: 'IL',
    zip: '60601',
    phone: '312-123-4567',
    email: 'info@urbanoasis.com',
    website: 'https://urbanoasis.com',
    services: ['Haircut', 'Coloring', 'Styling', 'Spa', 'Massage', 'Facials'],
    employees: [],
    ratings: [],
    covidSafety: 4,
    user: '6462e5a7e0a71fef963dc856',
  },
  {
    name: 'EcoGlam Spa',
    description: 'Sustainable beauty with a touch of glamour',
    address: '200 Nature Drive',
    city: 'Austin',
    state: 'TX',
    zip: '78701',
    phone: '512-222-3333',
    email: 'contact@ecoglam.com',
    website: 'https://ecoglam.com',
    services: ['Haircut', 'Coloring'],
    employees: [],
    ratings: [],
    covidSafety: 5,
    user: '6462e5a7e0a71fef963dc856',
  },
  {
    name: 'Natural Elements',
    description: 'Environmentally conscious salon for natural beauty',
    address: '310 Green Rd',
    city: 'Portland',
    state: 'OR',
    zip: '97205',
    phone: '503-333-4444',
    email: 'info@naturalelements.com',
    website: 'https://naturalelements.com',
    services: ['Haircut', 'Organic Coloring', 'Massage'],
    employees: [],
    ratings: [],
    covidSafety: 5,
    user: '6462e5a7e0a71fef963dc856',
  },
  {
    name: 'Elegance Studio',
    description: 'Where sophistication meets style',
    address: '142 Chic Blvd',
    city: 'Dallas',
    state: 'TX',
    zip: '75201',
    phone: '214-555-6666',
    email: 'elegance@studiostyle.com',
    website: 'https://elegancestudio.com',
    services: ['Styling', 'Makeup', 'Nails'],
    employees: [],
    ratings: [],
    covidSafety: 4,
    user: '64c3613ac2b3a17dda9ad1a5',
  },
  {
    name: 'Blossom Beauty Lounge',
    description: 'Where elegance meets natural beauty',
    address: '330 Rose Ave',
    city: 'Los Angeles',
    state: 'CA',
    zip: '90001',
    phone: '323-444-5555',
    email: 'blossom@beautylounge.com',
    website: 'https://blossombeauty.com',
    services: ['Haircut', 'Coloring', 'Spa', 'Massage', 'Facials'],
    employees: [],
    ratings: [],
    covidSafety: 4,
    user: '64c3613ac2b3a17dda9ad1a5',
  },
  {
    name: 'Serene Escape Spa',
    description: 'A serene escape from the everyday',
    address: '77 Calm Street',
    city: 'San Francisco',
    state: 'CA',
    zip: '94101',
    phone: '415-666-7777',
    email: 'serene@escapespa.com',
    website: 'https://sereneescape.com',
    services: ['Haircut', 'Coloring', 'Styling', 'Spa', 'Massage', 'Facials'],
    employees: [],
    ratings: [],
    covidSafety: 5,
    user: '64c3613ac2b3a17dda9ad1a5',
  },
  {
    name: 'Heavenly Touch Salon',
    description: 'Experience a touch of heaven on earth',
    address: '100 Angelic Blvd',
    city: 'Miami',
    state: 'FL',
    zip: '33101',
    phone: '305-888-9999',
    email: 'heavenly@touchsalon.com',
    website: 'https://heavenlytouch.com',
    services: ['Haircut', 'Coloring', 'Styling', 'Spa', 'Massage', 'Facials'],
    employees: [],
    ratings: [],
    covidSafety: 4,
    user: '64c3613ac2b3a17dda9ad1a5',
  },
  {
    name: 'Chic Retreat Salon & Spa',
    description: 'The chic destination for relaxation',
    address: '25 Trendy Lane',
    city: 'New York',
    state: 'NY',
    zip: '10001',
    phone: '212-101-2020',
    email: 'chic@retreatsalon.com',
    website: 'https://chicretreat.com',
    services: ['Haircut', 'Coloring', 'Facials'],
    employees: [],
    ratings: [],
    covidSafety: 5,
    user: '64c3613ac2b3a17dda9ad1a5',
  },
  {
    name: 'Majestic Waves Salon',
    description: 'Majestic beauty at its finest',
    address: '555 Ocean View Rd',
    city: 'San Diego',
    state: 'CA',
    zip: '92101',
    phone: '619-333-4444',
    email: 'majestic@wavessalon.com',
    website: 'https://majesticwaves.com',
    services: ['Haircut', 'Coloring', 'Styling', 'Spa', 'Massage', 'Facials'],
    employees: [],
    ratings: [],
    covidSafety: 4,
    user: '64c3613ac2b3a17dda9ad1a5',
  },
  {
    name: 'Eden Beauty Spa',
    description: 'A paradise of pampering and relaxation',
    address: '777 Paradise Rd',
    city: 'Las Vegas',
    state: 'NV',
    zip: '89101',
    phone: '702-555-6666',
    email: 'eden@beautyspa.com',
    website: 'https://edenbeautyspa.com',
    services: ['Haircut', 'Coloring', 'Styling', 'Spa', 'Massage', 'Facials'],
    employees: [],
    ratings: [],
    covidSafety: 5,
    user: '64c3613ac2b3a17dda9ad1a5',
  },
  {
    name: 'Harmony Hair & Spa',
    description: 'Experience the harmony of beauty and relaxation',
    address: '303 Harmony St',
    city: 'Nashville',
    state: 'TN',
    zip: '37201',
    phone: '615-777-8888',
    email: 'harmony@hairspa.com',
    website: 'https://harmonyhairspa.com',
    services: ['Haircut', 'Coloring', 'Styling', 'Spa', 'Massage', 'Facials'],
    employees: [],
    ratings: [],
    covidSafety: 4,
    user: '64c3613ac2b3a17dda9ad1a5',
  },
  {
    name: 'Tranquil Trends Salon',
    description: 'Trendy styles in a tranquil setting',
    address: '444 Peace Ave',
    city: 'Denver',
    state: 'CO',
    zip: '80201',
    phone: '303-999-1111',
    email: 'tranquil@trendssalon.com',
    website: 'https://tranquiltrends.com',
    services: ['Haircut', 'Coloring', 'Styling', 'Spa', 'Massage', 'Facials'],
    employees: [],
    ratings: [],
    covidSafety: 5,
    user: '64c3613ac2b3a17dda9ad1a5',
  },
  {
    name: 'Glow and Grace Salon',
    description: 'For the grace and glow that shines within',
    address: '250 Shimmer St',
    city: 'Houston',
    state: 'TX',
    zip: '77001',
    phone: '713-222-3333',
    email: 'glow@gracesalon.com',
    website: 'https://glowandgrace.com',
    services: ['Haircut', 'Coloring', 'Styling', 'Spa', 'Massage', 'Facials'],
    employees: [],
    ratings: [],
    covidSafety: 4,
    user: '64c3613ac2b3a17dda9ad1a5',
  },
  {
    name: 'Rejuvenate Salon & Wellness',
    description: 'Revive your beauty and wellness',
    address: '505 Revive Rd',
    city: 'Phoenix',
    state: 'AZ',
    zip: '85001',
    phone: '602-444-5555',
    email: 'rejuvenate@salonwellness.com',
    website: 'https://rejuvenatesalon.com',
    services: [ 'Spa' ],
    employees: [],
    ratings: [],
    covidSafety: 5,
    user: '64c3613ac2b3a17dda9ad1a5',
  },
  {
    name: 'Elegant Embrace Spa',
    description: 'Embrace your elegance and grace',
    address: '180 Elegance Blvd',
    city: 'Indianapolis',
    state: 'IN',
    zip: '46201',
    phone: '317-666-7777',
    email: 'elegant@embracespa.com',
    website: 'https://elegantembrace.com',
    services: ['Haircut', 'Coloring', 'Styling', 'Spa', 'Massage', 'Facials'],
    employees: [],
    ratings: [],
    covidSafety: 4,
    user: '64c3613ac2b3a17dda9ad1a5',
  },
  {
    name: 'Mystic Beauty Lounge',
    description: 'Mystical beauty in a luxurious setting',
    address: '360 Mystic Ave',
    city: 'Atlanta',
    state: 'GA',
    zip: '30301',
    phone: '404-888-9999',
    email: 'mystic@beautylounge.com',
    website: 'https://mysticbeautylounge.com',
    services: ['Haircut', 'Coloring', 'Styling', 'Spa', 'Massage', 'Facials'],
    employees: [],
    ratings: [],
    covidSafety: 5,
    user: 'someUserId14',
  },
  {
    name: 'Luxury Locks Salon',
    description: 'Luxury and style in one place',
    address: '525 Luxury Lane',
    city: 'Boston',
    state: 'MA',
    zip: '02101',
    phone: '617-444-5555',
    email: 'luxury@lockssalon.com',
    website: 'https://luxurylocks.com',
    services: [  'Facials'],
    employees: [],
    ratings: [],
    covidSafety: 4,
    user: '64c3613ac2b3a17dda9ad1a5',
  },
  {
    name: 'Radiant Retreat Spa & Salon',
    description: 'Radiate beauty at your next retreat',
    address: '720 Radiant Rd',
    city: 'Philadelphia',
    state: 'PA',
    zip: '19101',
    phone: '215-777-8888',
    email: 'radiant@retreatspa.com',
    website: 'https://radiantretreat.com',
    services: ['Haircut', 'Coloring', 'Styling', 'Spa', 'Massage', 'Facials'],
    employees: [],
    ratings: [],
    covidSafety: 5,
    user: '64c3613ac2b3a17dda9ad1a5',
  },
  {
    name: 'Pure Bliss Salon',
    description: 'Discover pure bliss and relaxation',
    address: '999 Bliss Blvd',
    city: 'Columbus',
    state: 'OH',
    zip: '43201',
    phone: '614-222-3333',
    email: 'pure@blisssalon.com',
    website: 'https://purebliss.com',
    services: ['Haircut', 'Coloring', 'Styling'],
    employees: [],
    ratings: [],
    covidSafety: 4,
    user: '64c3613ac2b3a17dda9ad1a5',
  },
  {
    name: 'Timeless Trends Spa',
    description: 'Timeless beauty and trending styles',
    address: '400 Timeless St',
    city: 'Detroit',
    state: 'MI',
    zip: '48201',
    phone: '313-444-5555',
    email: 'timeless@trendsspa.com',
    website: 'https://timelesstrends.com',
    services: [ 'Coloring'],
    employees: [],
    ratings: [],
    covidSafety: 5,
    user: '64c3613ac2b3a17dda9ad1a5',
  },
  {
    name: 'Nature Nurtured Salon',
    description: 'Nurturing natural beauty in a calm setting',
    address: '525 Natural Way',
    city: 'Baltimore',
    state: 'MD',
    zip: '21201',
    phone: '410-666-7777',
    email: 'nature@nurturedsalon.com',
    website: 'https://naturenurtured.com',
    services: [ 'Styling'],
    employees: [],
    ratings: [],
    covidSafety: 4,
    user: '64c3613ac2b3a17dda9ad1a5',
  },
  {
    name: 'Signature Styles Salon',
    description: 'Stylish signatures for every individual',
    address: '777 Signature St',
    city: 'Charlotte',
    state: 'NC',
    zip: '28201',
    phone: '704-333-4444',
    email: 'signature@stylessalon.com',
    website: 'https://signaturestyles.com',
    services: ['Haircut'],
    employees: [],
    ratings: [],
    covidSafety: 5,
    user: '64c3613ac2b3a17dda9ad1a5',
  },
]

mongoose
  .connect(dbURI, { useNewUrlParser: true, useUnifiedTopology: true })
  .then(async () => {
    console.log('Connected to database')

    const collections = await mongoose.connection.db.listCollections().toArray()
    const collectionExists = collections.some((col) => col.name === 'salons')

    if (collectionExists) {
      console.log('Collection exists, trying to drop it...')
      try {
        await mongoose.connection.db.dropCollection('salons')
        console.log('Collection dropped')
        insertData()
      } catch (err) {
        console.log('Error in dropping collection:', err)
      }
    } else {
      console.log('Collection does not exist, trying to insert data...')
      insertData()
    }
  })
  .catch((err) => console.log('Database connection failed:', err))

function insertData() {
  Salon.insertMany(seedData)
    .then((res) => {
      console.log('Data seeded')
      mongoose.connection.close()
    })
    .catch((err) => {
      console.log('Error in seeding data:', err)
      mongoose.connection.close()
    })
}
